export const CHANGE_NOTIFICATION = "CHANGE_NOTIFICATION";

export const SET_ACTIVITY_HOURS = "SET_ACTIVITY_HOURS";
export const SET_GENERAL_COMPANY_STATUS = "SET_GENERAL_COMPANY_STATUS";
export const SET_IN_PROGRESS_COURSES = "SET_IN_PROGRESS_COURSES";
export const SET_SKILL_IN_DEVELOPMENT = "SET_SKILL_IN_DEVELOPMENT";
export const SET_TEAMS = "SET_TEAMS";
export const SET_TOP_EMPLOYEES = "SET_TOP_EMPLOYEES";
export const SET_TOP_SKILLS = "SET_TOP_SKILLS";
export const SET_UPCOMING_COURSES = "SET_UPCOMING_COURSES";
export const SET_DATAGRID = "SET_DATAGRID";

export const SET_SELECTED_TEAMS = "SET_SELECTED_TEAMS";
export const DELETE_TEAMS = "DELETE_TEAMS";
export const ADD_TEAM = "ADD_TEAM";
export const HANDLE_CHANGE_TEAM = "HANDLE_CHANGE_TEAM";
export const SET_SELECTED_EMPLOYEE = "SET_SELECTED_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const HANDLE_CHANGE_EMPLOYEE = "HANDLE_CHANGE_EMPLOYEE";
export const SET_SELECTED_EMPLOYEE_INITIAL = "SET_SELECTED_EMPLOYEE_INITIAL";
