export const TEAM_CORE_DETAILS = "TEAM_CORE_DETAILS";
export const ORGANIZATION = "ORGANIZATION";
export const DATAGRID = "DATAGRID";
export const AVARAGE_EMPLOYEE_SCORE = "AVARAGE_EMPLOYEE_SCORE";
export const COMPLETED_COURSE = "COMPLETED_COURSE";
export const TOTAL_EMPLOYEE = "TOTAL_EMPLOYEE";
export const TOP_EMPLOYEE_DATAGRID = "TOP_EMPLOYEE_DATAGRID";
export const TOP_SKILL_DATAGRID = "TOP_SKILL_DATAGRID";
export const TOP_EMPLOYEE_BAR = "TOP_EMPLOYEE_BAR";
export const TOP_SKILL_BAR = "TOP_SKILL_BAR";
export const TIME_LINE = "TIME_LINE";
export const SKILLS_DEVELOPMENT_DATAGRID = "SKILLS_DEVELOPMENT_DATAGRID";
export const SKILLS_DEVELOPMENT_BAR = "SKILLS_DEVELOPMENT_BAR";
export const IN_PROGRESS_COURSE = "IN_PROGRESS_COURSE";
export const UP_COMING_COURSE = "UP_COMING_COURSE";

//teams
export const TEAM_EMPLOYEE = "TEAM_EMPLOYEE";
export const TEAM_OVERALL_SCORE = "TEAM_OVERALL_SCORE";
export const TEAM_TOTAL_EMPLOYEE = "TEAM_TOTAL_EMPLOYEE";
export const TEAM_EMPLOYEE_DETAIL = "TEAM_EMPLOYEE_DETAIL";
